<?php

/**
 * Implements hook_file_url_alter().
 *
 * Add file version token for all file urls that use file_create_url().
 *
 * @see file_create_url()
 */
function file_version_file_url_alter(&$uri) {
  $original_uri = $uri;
  $fileVersion = \Drupal::service('file_version');
  $fileSystem = \Drupal::service('file_system');
  $streamWrapperManager = \Drupal::service('stream_wrapper_manager');

  $scheme = $fileSystem->uriScheme($uri);

  if ($scheme) {
    if (
          !$fileVersion->isProtocolByPassed($scheme)
      &&  $wrapper = $streamWrapperManager->getViaUri($uri)
    ) {
      $uri = $wrapper->getExternalUrl();
    }
  }

  $fileVersion->addFileVersionToken($uri, $original_uri);
}
