<?php

/**
 * @file
 * Installation functions for File Version module.
 */

/**
 * Implements hook_install().
 */
function file_version_install() {
  // Ensure that custom or contrib hook_file_url_alter() runs
  // before than file_version.
  module_set_weight('file_version', 1);
}

/**
 * Update file_version weight for run after custom or contrib modules.
 */
function file_version_update_8001() {
  module_set_weight('file_version', 1);
}
