file_version.settings:
  type: config_object
  mapping:
    enable_image_styles:
      type: boolean
      label: 'Enable File Version for image styles'
    enable_all_files:
      type: boolean
      label: 'Enable File Version for all files'
    get_parameter_name:
      type: string
      label: 'The name of the GET url parameter for the file version token'
    extensions_blacklist:
      type: string
      label: 'Extensions to exclude'
    extensions_whitelist:
      type: string
      label: 'Extensions to include'
